# Generated by Django 5.0.6 on 2024-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Self Help', 'Self Help'), ('Fantasia', 'Fantasia'), ('Horror', 'Horror'), ('Historical Fiction', 'Historical Fiction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
